/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uprotocol.java.ulink.zenoh;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ULinkTest {
    @Test void appHasAGreeting() {
        ULink classUnderTest = new ULink();
        assertTrue( true );
    }
}
